### ISSUE TITLE
Check and fix argument ordering in test assertions

### ISSUE THREAD

**Issue by ikbalkaya** [ably/ably-java#892] opened 2023-01-11 11:44 UTC
Minor observation, and I recognise that lots of other sites in this codebase do this wrong, but the JUnit API wants `expected` first, followed by `actual`, as this ordering is used in some of the log messages it outputs. Therefore, for this line:

```suggestion
            assertEquals("Verify connected state reached", ConnectionState.connected, ably.connection.state);
```

This also applies to a few other asserts in this test method.

_Originally posted by @QuintinWillison in https://github.com/ably/ably-java/pull/887#discussion_r1066874493_

**Comment by QuintinWillison** [comment] 2023-01-11 11:46
Duplicate of https://github.com/ably/ably-java/issues/582.

**Closed** 2023-01-11 11:58 UTC
Labels: code-quality
