### ISSUE TITLE
Aeroplane mode appears to be removing listeners

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#170] opened 2016-09-29 20:38 UTC
This from a client:

> publish handler. so i go into aeroplane mode which ultimately suspends the connection. i come out of aeroplane mode. the client eventually re-connects. i then attach my channel manually as is required because of the suspend. then i publish a message, and in the publish call i create a new CompletionListener .. but onSuccess and onFailure are never called. The message *is* sent successfully though

We need to test to see if this is an Android issue (most likely) or something else, perhaps at a protocol level (we should add protocol message logging first, see https://github.com/ably/ably-java/issues/169#issue-180126091)

**Comment by trenouf** [comment] 2016-10-05 17:14
I think I have reproduced this on JRE. It looks like an ack comes back from the publish and I get an exception processing it:

18:08:44.256 [DEBUG] [TestEventLogger]     Caused by: java.lang.IllegalArgumentException: fromIndex(0) > toIndex(-4)
18:08:44.256 [DEBUG] [TestEventLogger]          at java.util.ArrayList.subListRangeCheck(ArrayList.java:1006)
18:08:44.256 [DEBUG] [TestEventLogger]          at java.util.ArrayList.subList(ArrayList.java:996)
18:08:44.257 [DEBUG] [TestEventLogger]          at io.ably.lib.transport.ConnectionManager$PendingMessageQueue.ack(ConnectionManager.java:809)
18:08:44.257 [DEBUG] [TestEventLogger]          at io.ably.lib.transport.ConnectionManager.onAck(ConnectionManager.java:370)

**Comment by trenouf** [comment] 2016-10-05 23:43
I have a fix for this. I will push it, with a test, tomorrow.

**Closed** 2016-10-10 19:06 UTC
Labels: bug
