### ISSUE TITLE
Missing Maven dependency

### ISSUE THREAD

**Issue by azzazzel** [ably/ably-java#533] opened 2019-11-25 22:11 UTC
Hi folks,

I tried to use the java client and it turns out `io.ably:ably-java:1.1.5` depends on `io.ably:Java-WebSocket:1.3.1` but that artifact is not in Maven central. Unless you have `http://jcenter.bintray.com` repository added to the POM, Maven can't find the dependency and the build fails. Please consider releasing the artifact to Maven Central. 

On a related note - none of the `1.1.6` artifacts are in Maven central even though they have been published on jcenter on Nov 15. If you auto-sync with Maven Central perhaps you should check your process. If your strategy is to only use jcenter you should probably document that in a prominent place as most Java developers would expect your artifacts to be on Maven Central.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-573) by [Unito](https://www.unito.io/learn-more)

**Comment by paddybyers** [comment] 2019-11-25 22:22
We do only support JCenter right now, and this is stated: https://github.com/ably/ably-java#installation.

We do have work in progress to support Maven Central also (https://github.com/ably/ably-java/pull/506) and that will be released soon.

**Comment by azzazzel** [comment] 2019-11-25 22:44
Oh, my bad. I should have paid attention to the README. I was just following the examples on Ably Hub to play around with consuming realtime data. As there are no installation instructions there I simply assumed I'll find the artifacts on maven central and then googled my way to jcenter. I only came to this repo afterwards to report the issue. 

I still think having broken artifact in Maven Central is an issue but feel free to close this if you disagree.

**Comment by benwaine** [comment] 2020-02-12 11:51
Found my way here in exactly the same way as @azzazzel, assumed the examples on the website would be plug and play. 

Also no Maven section in the documentation showing how to set up the repository. 

It feels like a bit of a spikey developer experience at the moment.

**Comment by benwaine** [comment] 2020-02-12 12:03
For anyone hitting the same issue re configuring the Ably SDK using maven. 
```
 ... More POM ... 

    <dependencies>
        <dependency>
            <groupId>io.ably</groupId>
            <artifactId>ably-java</artifactId>
            <version>1.1.8</version>
        </dependency>
    </dependencies>

 ... More POM ...

    <repositories>
        <repository>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <id>bintray-ably-io-ably</id>
            <name>bintray</name>
            <url>https://dl.bintray.com/ably-io/ably</url>
        </repository>
     </repositories>
 ... 
```

**Comment by QuintinWillison** [comment] 2022-05-12 09:30
Closing this issue as the problem is no long present. Bintray / JCenter is no more. 😢

**Closed by QuintinWillison** 2022-05-12 09:30 UTC
Labels: build
