### ISSUE TITLE
Race condition releasing short lived channels

### ISSUE THREAD

**Issue by nickmbailey** [ably/ably-java#570] opened 2020-03-19 21:24 UTC
I've noticed a race condition when creating and releasing channels in a fairly small time window.

It seems like its possible to create a channel, receive a message on it, then detach and release it, all before getting the 'attached' response from ably.

When this happens, the Channels.onMessage function calls 'channels.get':

https://github.com/ably/ably-java/blob/v1.1.10/lib/src/main/java/io/ably/lib/realtime/AblyRealtime.java#L178

This causes the channel to be recreated in an 'initialized' state again since it doesn't exist in the channels map.

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-455) by [Unito](https://www.unito.io)

**Comment by paddybyers** [comment] 2020-03-19 21:30
Hi, thanks for raising this. We'll have a look.

**Comment by QuintinWillison** [comment] 2020-03-20 11:47
Hello @nickmbailey. Thanks for the report - this should be pretty easy to reproduce at our end so we'll do that first so we can work out what needs to change to stop it happening.

I'm pretty sure that we'll be able to reproduce this, though I'm not sure when that will happen as we have quite a lot going on right now. In the meantime, until we can find the time to look at this closer, it might help us flesh out the exact scenario if you were able to provide a snippet of example code illustrating what you did to make this happen. If you have the time over the next week or so to do that then that would be appreciated.

Finally, may I ask if this bug is blocking you doing what you need to do with the library or have you found a suitable workaround?

**Comment by nickmbailey** [comment] 2020-03-20 14:15
For now, my workaround is to manually attach the channel, block on the completion success listener, then continue on as normal. Which seems to work fine.

I can probably come up with a simple repro script if clojure is acceptable for that.

**Comment by QuintinWillison** [comment] 2020-03-20 14:17
That would be helpful, if you don't mind. Clojure would be perfect. Thanks!

**Comment by nickmbailey** [comment] 2020-03-20 16:37
Here's a quick script that demonstrates the issue. At the end of the run fn it always finds the 'released' channel with an initialized state. In my real world use case where multiple channels were in play I would sometimes find channels that got reattached and left in an attached state.

```clojure
(ns ably-bug
  (:import
    [io.ably.lib.rest AblyRest]
    [io.ably.lib.realtime AblyRealtime
                          Channel$MessageListener]))

(defn subscribe
  [ably-ws channel-name]
  (let [channels (.channels ably-ws)
        channel (.get channels channel-name)
        msg-promise (promise)
        listener (reify Channel$MessageListener
                   (onMessage [this msg]
                     (deliver msg-promise msg)
                     (println "Got Message: " msg)))]
    (.subscribe channel listener)
    [msg-promise #(.release channels channel-name)]))

(defn send-message
  [ably-http channel-name message]
  (let [channel (-> ably-http .channels (.get channel-name))]
    (.publish channel "" message)))

(defn run
  []
  (let [api-key "<INSERT KEY HERE>"
        ably-ws (AblyRealtime. api-key)
        ably-http (AblyRest. api-key)

        channel-name "foo"
        ; add rewind param in case the message gets there before the subscribe succeeds since this
        ; test is all local
        subscribe-channel-name (format "[?rewind=1]%s" channel-name)
        [p unsubscribe-fn] (subscribe ably-ws subscribe-channel-name)]

    ; send a message via http client
    (send-message ably-http channel-name "bar")

    ; block on getting a message via ws client
    @p

    ; unsubscribe (release) channel
    (unsubscribe-fn)

    ; sleep since detaching is async although the removal from the channels map should be
    ; immediate
    (Thread/sleep 5000)

    ; channels should be empty
    (doseq [[channel-name channel] (-> ably-ws .channels .entrySet)]
      (println (format "Found channel %s with state %s" channel-name (.state channel))))

    (.close ably-ws)))
```

**Comment by QuintinWillison** [comment] 2020-03-20 16:39
Thank you so much. I'm not in a position to try it today but this will be really useful when we come to debugging this one. 😀

**Comment by jamienewcomb** [comment] 2021-06-02 17:11
(i have asked Martin to comment in github first so we avoid seeing sync-bot commenting)

@sacOO7 could you check Martin's understanding please (https://github.com/ably/ably-java/issues/570#issuecomment-852093679)

**Comment by sacOO7** [comment] 2021-06-03 00:06
> ➤ Martin Morek commented:
> 
> What should be the correct behaviour?
> 
> When: create a channel -> receive a message on it -> detach it -> release it, and if then check channel state, it should be “attached”, or this channel shouldn’t exist at all since it was released?

The general flow is, channelnitialized -> channelAttaching-> ChanelAttached-> receive messages -> channel detaching -> channel detached/suspended/failed

**Comment by martin-morek** [comment] 2021-06-16 18:58
I've tried to create a test scenario (in java) to reproduce this bug, however I didn't succeed. It always reaches correct (`attached`) state when message is received. I've followed the Clojure code (not sure if 100% correctly). If I release channel and get it again, it truly has `initialized` state but that correct since it's new channel. I'm including the test code, please correct me if I'm missing something. 

```java
@Test
    public void attached_state_is_correctly_achieved() {
        String channelName = "test_" + testParams.name;
        AblyRealtime ably = null;

        try {
            ClientOptions opts = createOptions(testVars.keys[0].keyStr);
            ably = new AblyRealtime(opts);

            /* wait until connected */
            (new ConnectionWaiter(ably.connection)).waitFor(ConnectionState.connected);
            assertEquals("Verify connected state reached", ably.connection.state, ConnectionState.connected);


            final Map<String, String> params = new HashMap<>();
            params.put("rewind", "1");
            final ChannelOptions options = new ChannelOptions();
            options.params = params;

            Channel channel = ably.channels.get(channelName, options);
            channel.publish("", "test-message");

            // channel is in initialized state when created
            assertEquals(ChannelState.initialized, channel.state);

            Helpers.MessageWaiter messageWaiter = new Helpers.MessageWaiter(channel);
            // channel is not attached yet
            assertEquals(ChannelState.attaching, channel.state);

            messageWaiter.waitFor(1);
            // when message is received channel state is already `attached` 
            assertEquals(ChannelState.attached, channel.state);

            ably.channels.release(channelName);

            // verify there are no channels after realising 
            assertFalse(ably.channels.entrySet().iterator().hasNext());

            // get state again
            channel = ably.channels.get(channelName, options);
            assertEquals(ChannelState.initialized, channel.state);
        } catch (AblyException e) {
            e.printStackTrace();
            fail("init0: Unexpected exception instantiating library");
        } finally {
            if(ably != null)
                ably.close();
        }
    }

**Comment by nickmbailey** [comment] 2021-06-16 19:45
I haven't looked at this in a long time but in my initial test code I believe the five second sleep is required. When you call 'release' the channel is removed immediately and at some indeterminate time in the future an 'ATTACHED' message comes in from the server which causes the channel to be recreated.

The other difference i see is that my test uses the http client for publishing the messages but I don't know if that changes anything.

**Comment by martin-morek** [comment] 2021-06-22 12:39
I've also tired with a delay but got the same result.

**Comment by QuintinWillison** [comment] 2021-07-21 04:45
This is a pernicious one. Clearly #679 does not reproduce, nor solve, the issue being reported.

Perhaps relates to https://github.com/ably/ably-java/issues/662?

**Comment by QuintinWillison** [comment] 2021-07-27 12:53
Closing this issue as we've been unable to reproduce. I'm sure there was/is something there, and hopefully we'll pick that up in due course (perhaps under #662).

**Closed by QuintinWillison** 2021-07-27 12:53 UTC
Labels: bug
