### ISSUE TITLE
Threads remain in parked (waiting) state indefinitely when `AblyRest` instance is freed

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-java#801] opened 2022-06-20 08:49 UTC
We've had a [report](https://ably-real-time.slack.com/archives/C02C0CNCPTK/p1655701678874329?thread_ts=1655536688.502499&cid=C02C0CNCPTK) from a customer:

> we have noticed that when an instance of the AblyRest is replaced by another instance (as part of regenerating the client), the threads held by the old instance is not getting released or destroyed. This causes the threads to keep increasing as new instances of AblyRest gets created.
>
> The threads are managed by the ThreadpoolExecutor in the AsyncHttpScheduler and a max of 64 (default) can get created. They are placed in parked (waiting) state indefinitely. These threads continue to remain in this state even after the AblyRest instance in which they belong to is removed.
>
> It seems the AsyncHttpScheduler.dispose method is not getting called in this case.
>
> This is causing the jvm memory usage to slowly increase over time.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2062) by [Unito](https://www.unito.io)

**Comment by paddybyers** [comment] 2022-06-20 09:04
I think the issue is simply that the REST library doesn't have a lifecycle in the way that realtime does. You create the library, and you don't dispose the library, which would ordinarily dispose of resources. So either I think we need to make that lifecycle explicit (which I would prefer to avoid for the REST client) or have idle threads eventually exit so all resources are released without explicit action.

**Closed** 2022-06-22 13:05 UTC
Labels: bug
